files:
  - source: /docs/getting-started/**
    translation: /docs_%two_letters_code%/getting-started/%file_name%.%file_extension%
  - source: docs/user-guide/**
    translation: /docs_%two_letters_code%/user-guide/%file_name%.%file_extension%
  - source: docs/library-packs/**
    translation: /docs_%two_letters_code%/library-packs/applications/%file_name%.%file_extension%
